#include "MaxHeap.h"
#include "MinHeap.h"
#include "MedianHeap.h"
#include <iostream>
using namespace std;
int main() {

    cout << "MaxHeap Test:" << endl;
    MaxHeap x;
    cout << "Insert 14: ";
    x.insert(14);
    x.printMaxHeap();
    cout << "Insert 16: ";
    x.insert(16);
    x.printMaxHeap();
    cout << "Insert 10: ";
    x.insert(10);
    x.printMaxHeap();
    cout << "Insert 23: ";
    x.insert(23);
    x.printMaxHeap();
    cout << "Insert 1: ";
    x.insert(1);
    x.printMaxHeap();
    cout << "Insert 9: ";
    x.insert(9);
    x.printMaxHeap();
    cout << "Insert 22: ";
    x.insert(22);
    x.printMaxHeap();
    cout << "Insert 2: ";
    x.insert(2);
    x.printMaxHeap();
    cout << "Insert 7: ";
    x.insert(7);
    x.printMaxHeap();
    cout << "Insert 11: ";
    x.insert(11);
    x.printMaxHeap();
    int size = x.size();
    cout << "Size of the MaxHeap: " << size << endl;
    int top = x.peek();
    cout << "Peek (top) element: " << top << endl;
    cout << "Delete max element: ";
    int a = x.extractMax();
    x.printMaxHeap();
    cout << "Deleted element: " << a << endl;
    top = x.peek();
    cout << "Peek (top) element: " << top << endl;
    cout << "Delete max element: ";
    a = x.extractMax();
    x.printMaxHeap();
    cout << "Deleted element: " << a << endl;
    size = x.size();
    cout << "Size of the MaxHeap: " << size << endl;


    cout << "----------------------------------" << endl;
    cout << "MinHeap Test:" << endl;
    MinHeap y;
    cout << "Insert 7: ";
    y.insert(7);
    y.printMinHeap();
    cout << "Insert 16: ";
    y.insert(16);
    y.printMinHeap();
    cout << "Insert 10: ";
    y.insert(10);
    y.printMinHeap();
    cout << "Insert 23: ";
    y.insert(23);
    y.printMinHeap();
    cout << "Insert 1: ";
    y.insert(1);
    y.printMinHeap();
    cout << "Insert 9: ";
    y.insert(9);
    y.printMinHeap();
    cout << "Insert 22: ";
    y.insert(22);
    y.printMinHeap();
    cout << "Insert 2: ";
    y.insert(2);
    y.printMinHeap();
    cout << "Insert 7: ";
    y.insert(7);
    y.printMinHeap();
    cout << "Insert 11: ";
    y.insert(11);
    y.printMinHeap();
    int size2 = y.size();
    cout << "Size of the MinHeap: " << size2 << endl;
    int top2 = y.peek();
    cout << "Peek (top) element: " << top2 << endl;
    cout << "Delete min element: ";
    int a2 = y.extractMin();
    y.printMinHeap();
    cout << "Deleted element: " << a2 << endl;
    top2 = y.peek();
    cout << "Peek (top) element: " << top2 << endl;
    cout << "Delete min element: ";
    a2 = y.extractMin();
    y.printMinHeap();
    cout << "Deleted element: " << a2 << endl;
    size2 = y.size();
    cout << "Size of the MinHeap: " << size2 << endl;

    cout << "----------------------------------" << endl;
    cout << "MedianHeap Test:" << endl;
    MedianHeap z;
    z.insert(14);
    z.insert(16);
    z.insert(10);
    z.insert(8);
    z.insert(3);
    z.insert(9);
    z.insert(4);
    z.insert(2);
    z.insert(1);
    z.insert(7);
//    z.insert(1);
//    z.insert(2);
//    z.insert(3);
//    z.insert(14);
//    z.insert(1);
//    z.insert(9);
//    z.insert(4);
//    z.insert(2);
//    z.insert(1);
//    z.insert(7);
    int median = z.findMedian();
    cout << "Median is: " << median << endl;
    return 0;
}
